name: Build Deb Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run : echo 'building'
        
      
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.2'

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies
          
          
      - name: prepare_debian_package
        run: |
          cabal build
          
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/share/doc/xnec2c-gao/
          
          cabal install --install-method=copy --installdir=./.debpkg/usr/bin/
          cp -r examples/ ./.debpkg/usr/share/doc/xnec2c-gao/
          

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
          echo "Github Ref: " ${{github.ref}}
      
      
      - name: build_deb_package
        id: debian_package
        uses: jiro4989/build-deb-action@v2
        with:
            package: xnec2c-gao
            package_root: .debpkg
            maintainer: Maurizio Di Pietro DC1MDP <dc1mdp@gmail.com>
            version: ${{ github.ref }} # refs/tags/v*.*.*
            arch: 'amd64'
            depends: 'libc6 (>= 2.34), libgmp10 (>= 2:6.2.1+dfsg1), libnuma1 (>= 2.0.11)'
            desc: 'An external optimizer for xnec2c based on genetic algorithm'
      
#     - name: publish_debian_package
#       uses: planet-code/upload-to-release-action@1.0.0
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         asset-path: ${{steps.debian_package.outputs.file_name}}

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: xnec2c-gao
          body: >
            This release actually changes the fabric of the reality, so be careful 
            while applying, as error in database migration, can irrecoverably wipe 
            some laws of physics.  
          gzip: folders
          files: ${{steps.debian_package.outputs.file_name}}
