name: Pandoc Readme

on: 
  push:
    branches : master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run : echo 'building'
        
      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@master
        with:
          args: '-s -N --toc -t latex  README.md metadata.yml -o README.pdf'
  
      
