name: Pandoc Readme

on: 
  push:
    branches : master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run : echo 'building'
        
      - name: Pandoc Document Converter
        uses: Ender-events/pandoc@master
        with:
          args: '-s -N --toc -t pdf -o README.pdf README.md metadata.yml'
  
      
